### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by blackhuman** [oleg-liatte/proxychains-multi#1]
just download and make and make install your newest code. But after i configured properly, and then run it with command `proxychains-multi wget www.google.com.hk` i got _syntax error_ which looks like:

> Resolving www.google.com.hk... /etc/proxychains-multi.conf[47:1-47:1]: syntax error
> /etc/proxychains-multi.conf[47:1-47:1]: syntax error
> /etc/proxychains-multi.conf[47:1-47:1]: syntax error
> /etc/proxychains-multi.conf[47:1-47:1]: syntax error
> Connecting to www.google.com.hk|74.125.128.199|:80... /etc/proxychains-multi.conf[47:1-47:1]: syntax error

and then, it connect the web directly, rather than connect through the socks5 proxy which i configured before.

**Comment by oleg-liatte** [comment]
Could you show contents of your `/etc/proxychains-multi.conf`? Especially line 47 (and probably 46).
